# Copyright (C) 2018-present Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (C) 2018-present Sven Greb <development@svengreb.de>

# Project:    Styleguide JavaScript
# Repository: https://github.com/arcticicestudio/styleguide-javascript
# License:    MIT
# References:
#   https://circleci.com/docs/2.0
#   https://circleci.com/docs/2.0/circleci-images/#nodejs

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: preprocess-clean-node-modules
          command: rm -rf node_modules
      - run:
          name: preprocess-yarn-install
          command: yarn install
      - run:
          name: lint
          command: yarn lint
      - run:
          name: generate-docs
          command: yarn docs:build
      - store_artifacts:
          path: build/docs
